### ISSUE TITLE
Clarify note about SnapMirror

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/asa-r2#12]
### Page URL

https://docs.netapp.com/us-en/asa-r2/data-protection/snapshot-replication.html

### Page title

Replicate snapshots to a remote cluster from ASA r2 storage systems

### Summary

The note currently reads as:
"Snapshot replication from an ASA r2 storage system is supported only to another ASA r2 storage system.  You cannot replicate snapshots from an  ASA r2 system to a current ASA, AFF or FAS system."

But the limitation works the other way as well. You can't SnapMirror from current ASA, AFF or FAS systems to ASA r2. Can we clarify the note to include this direction as well? Otherwise we are going to get Support cases.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Joey,
Thank you for the feedback. Then note is updated.
