### ISSUE TITLE
Does NVMe/FC protocol support direct paths between the host and the ASA r2 storage?

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/asa-r2#18]
### Page URL

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html

### Page title

Learn about ASA r2 storage systems

### Summary

"ASA r2 systems support all SAN protocols (iSCSI, FC, NVMe/FC, NVMe/TCP) on a single HA-pair deployment. SCSI (iSCSI and FC) protocols use a symmetric active-active architecture for multipathing so that all paths between the hosts and storage are active/optimized. NVMe protocols support direct paths between the hosts and storage."

In the above ASA r2 document description, it states that "NVMe protocols support direct paths between the hosts and storage". 

However, for the NVMe/FC protocol, I believe that ASA r2 would still need FC switch with NPIV support for NVMe/FC LIFs to operate properly. 

If that is the case, perhaps that description should be changed to "iSCSI and NVMe/TCP protocols support direct paths between the hosts and storage."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@netapp-jyhshing thank you for the great feedback.  You are correct.  I've updated the documentation.
