### ISSUE TITLE
Do NOT support for SnapMirror to non-ASA r2 systems

### ISSUE THREAD

**Issue by adg331** [NetAppDocs/asa-r2#19]
### Page URL

https://docs.netapp.com/us-en/asa-r2/learn-more/software-support-limitations.html

### Page title

ONTAP software support and limitations for ASA r2 storage systems

### Summary

Can you elaborate what the SnapMirror stands for? Async or Sync or both not supported?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@adg331 it refers to Async and Sync.  I've added that clarification in the documentation.  Thank you for your feedback.
