### ISSUE TITLE
fix ONTAP 9.16.10

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/asa-r2#2]
### Page URL

https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9160.html

### Page title

What's new in ONTAP 9.16.0 for ASA r2 systems

### Summary

should say 9.16.0

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you Logan!
